apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opensearch-mcp
resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
images:
  - name: quay.io/mukrishn/opensearch-mcp-server
    newTag: "latest"
